; Generated by tools/gen_dxgi_exports.py from C:\Windows\System32\dxgi.dll (10.0.26100.9549), 20 exports. Regenerate, don't edit.
; Stub i jumps through g_dxgiReal[i], which main.cpp fills from the real System32\dxgi.dll. Nothing is
; pushed or changed, so the real function sees the caller's own call: arguments, stack and return address.
; Each stub starts a 16-byte slot of its own, like a compiled function: hooking tools (security software on the
; dev PC hooks CreateDXGIFactory*) overwrite the start of a function, some with a 14-byte jump, and that must
; not run into the next stub.
EXTERN g_dxgiReal:QWORD
.CODE
ALIGN 16
dxgi_stub_0 PROC ; ApplyCompatResolutionQuirking @1
    jmp QWORD PTR [g_dxgiReal + 0]
dxgi_stub_0 ENDP
ALIGN 16
dxgi_stub_1 PROC ; CompatString @2
    jmp QWORD PTR [g_dxgiReal + 8]
dxgi_stub_1 ENDP
ALIGN 16
dxgi_stub_2 PROC ; CompatValue @3
    jmp QWORD PTR [g_dxgiReal + 16]
dxgi_stub_2 ENDP
ALIGN 16
dxgi_stub_3 PROC ; DXGIDumpJournal @4
    jmp QWORD PTR [g_dxgiReal + 24]
dxgi_stub_3 ENDP
ALIGN 16
dxgi_stub_4 PROC ; PIXBeginCapture @5
    jmp QWORD PTR [g_dxgiReal + 32]
dxgi_stub_4 ENDP
ALIGN 16
dxgi_stub_5 PROC ; PIXEndCapture @6
    jmp QWORD PTR [g_dxgiReal + 40]
dxgi_stub_5 ENDP
ALIGN 16
dxgi_stub_6 PROC ; PIXGetCaptureState @7
    jmp QWORD PTR [g_dxgiReal + 48]
dxgi_stub_6 ENDP
ALIGN 16
dxgi_stub_7 PROC ; SetAppCompatStringPointer @8
    jmp QWORD PTR [g_dxgiReal + 56]
dxgi_stub_7 ENDP
ALIGN 16
dxgi_stub_8 PROC ; UpdateHMDEmulationStatus @9
    jmp QWORD PTR [g_dxgiReal + 64]
dxgi_stub_8 ENDP
ALIGN 16
dxgi_stub_9 PROC ; CreateDXGIFactory @10
    jmp QWORD PTR [g_dxgiReal + 72]
dxgi_stub_9 ENDP
ALIGN 16
dxgi_stub_10 PROC ; CreateDXGIFactory1 @11
    jmp QWORD PTR [g_dxgiReal + 80]
dxgi_stub_10 ENDP
ALIGN 16
dxgi_stub_11 PROC ; CreateDXGIFactory2 @12
    jmp QWORD PTR [g_dxgiReal + 88]
dxgi_stub_11 ENDP
ALIGN 16
dxgi_stub_12 PROC ; DXGID3D10CreateDevice @13
    jmp QWORD PTR [g_dxgiReal + 96]
dxgi_stub_12 ENDP
ALIGN 16
dxgi_stub_13 PROC ; DXGID3D10CreateLayeredDevice @14
    jmp QWORD PTR [g_dxgiReal + 104]
dxgi_stub_13 ENDP
ALIGN 16
dxgi_stub_14 PROC ; DXGID3D10GetLayeredDeviceSize @15
    jmp QWORD PTR [g_dxgiReal + 112]
dxgi_stub_14 ENDP
ALIGN 16
dxgi_stub_15 PROC ; DXGID3D10RegisterLayers @16
    jmp QWORD PTR [g_dxgiReal + 120]
dxgi_stub_15 ENDP
ALIGN 16
dxgi_stub_16 PROC ; DXGIDeclareAdapterRemovalSupport @17
    jmp QWORD PTR [g_dxgiReal + 128]
dxgi_stub_16 ENDP
ALIGN 16
dxgi_stub_17 PROC ; DXGIDisableVBlankVirtualization @18
    jmp QWORD PTR [g_dxgiReal + 136]
dxgi_stub_17 ENDP
ALIGN 16
dxgi_stub_18 PROC ; DXGIGetDebugInterface1 @19
    jmp QWORD PTR [g_dxgiReal + 144]
dxgi_stub_18 ENDP
ALIGN 16
dxgi_stub_19 PROC ; DXGIReportAdapterConfiguration @20
    jmp QWORD PTR [g_dxgiReal + 152]
dxgi_stub_19 ENDP
END
