#pragma once

// Generated by tools/gen_dxgi_exports.py from C:\Windows\System32\dxgi.dll (10.0.26100.9549), 20 exports. Regenerate, don't edit.
// kDxgiExports[i] is exported by dxgi_stub_i in dxgi_stubs.asm, which jumps through g_dxgiReal[i].

struct DxgiExport
{
    unsigned short ordinal;
    const char* name; // nullptr when exported by ordinal only
};

inline constexpr DxgiExport kDxgiExports[] = {
    { 1, "ApplyCompatResolutionQuirking" },
    { 2, "CompatString" },
    { 3, "CompatValue" },
    { 4, "DXGIDumpJournal" },
    { 5, "PIXBeginCapture" },
    { 6, "PIXEndCapture" },
    { 7, "PIXGetCaptureState" },
    { 8, "SetAppCompatStringPointer" },
    { 9, "UpdateHMDEmulationStatus" },
    { 10, "CreateDXGIFactory" },
    { 11, "CreateDXGIFactory1" },
    { 12, "CreateDXGIFactory2" },
    { 13, "DXGID3D10CreateDevice" },
    { 14, "DXGID3D10CreateLayeredDevice" },
    { 15, "DXGID3D10GetLayeredDeviceSize" },
    { 16, "DXGID3D10RegisterLayers" },
    { 17, "DXGIDeclareAdapterRemovalSupport" },
    { 18, "DXGIDisableVBlankVirtualization" },
    { 19, "DXGIGetDebugInterface1" },
    { 20, "DXGIReportAdapterConfiguration" },
};
